# Generated by Django 2.1.5 on 2019-02-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('ref_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('_id', models.IntegerField(blank=True, db_column='id', null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, db_column='type', max_length=255, null=True)),
                ('sq_feet', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('avdate', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rented', models.CharField(blank=True, max_length=255, null=True)),
                ('thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('thumb2', models.CharField(blank=True, max_length=255, null=True)),
                ('slide', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('marker', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_hidden', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('community', models.CharField(blank=True, max_length=255, null=True)),
                ('quadrant', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('den', models.CharField(blank=True, max_length=255, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('cats', models.IntegerField(blank=True, null=True)),
                ('dogs', models.IntegerField(blank=True, null=True)),
                ('utilities_included', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('retrieval_date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rental_data',
                'managed': False,
            },
        ),
    ]
